config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
     get '/user_profile', :to => 'registrations#show'
   end
  post 'payments/verify' => "payments#verify"
  resource :cart, only: [:show]
  resources :payments, only: [:new, :create]
  resources :order_items, only: [:create, :update, :destroy], format: :js
  resources :products do
    collection do
      get "order_history"
    end
  end
  resources :categories
  devise_for :users , :controllers => { registrations: 'registrations' }

  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    current_user.generate_pin
    current_user.send_pin
    respond_to do |format|
      format.js # render app/views/phone_numbers/create.js.erb
    end
  end
  def verify
    if current_user.verify(params[:pin])
      SendEmailMailer.welcome(current_user,current_order.order_items).deliver_now! rescue nil # send email to user upon successfull purchase
      current_order.order_items.each do |each_order|
        order = current_user.orders.create(product_id: each_order.product_id, user: current_user)
        order.update({total: each_order.total_price, quantity: each_order.quantity})
      end
    respond_to do |format|
      format.js # render app/views/phone_numbers/verify.js.erb
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/create.js.erb
$('#hidden_phone_number').val('<%= current_user.phone_number %>' )
$('#send-pin').hide()
$('#verify-pin').fadeToggle()
$('#pin').focus()

app/views/payments/new.html.erb
<div class="container">
<div id="send-pin">
<h3>What's your phone number?</h3>
<%= form_tag("/payments?product_id=#{params[:product_id]}", method: :post , remote: true) do %>
  <table>
    <tr>
      <td><%= label_tag :phone_number%></td>
      <td><%= text_field_tag :phone_number, current_user.phone_number%></td>
    </tr>
    <tr>
      <td><%= submit_tag "Send OTP" , class: "btn btn-primary", id: 'send-pin-link'%></td>
      <td></td>
    </tr>
  </table>
<%end%>
</div>

<div id="verify-pin">
<h3>Enter your PIN</h3>
<%= form_tag payments_verify_path(product_id: params[:product_id]), remote: true do |f| %>
  <%= hidden_field_tag 'hidden_phone_number', '' %>
  <div class="form-group">
    <%= text_field_tag :pin %>
  </div>
  <%= submit_tag "Verify PIN", class: "btn btn-primary" %>
  <% end %>
</div>

<div id="status-box" class="alert alert-success">
  <p id="status-message">Status: Haven’t done anything yet</p>
</div>
</div>

app/views/payments/verify.js.erb
<% if current_user.otp_verified %>
  <% current_user.update({otp_verified: false})%>
    $('#verify-pin').hide()
    $('#status-box').removeClass()
    $('#status-box').addClass('alert alert-success')
    $('#status-message').text('Success!!')
<% else %>
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("Sorry, that wasn't the right pin.")
<% end %>
$('#status-box').fadeToggle()