config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
     get '/user_profile', :to => 'registrations#show'
   end
  post 'payments/verify' => "payments#verify"
  resource :cart, only: [:show]
  resources :payments, only: [:new, :create]
  resources :order_items, only: [:create, :update, :destroy], format: :js
  resources :products do
    collection do
      get "order_history"
    end
  end
  resources :categories
  devise_for :users , :controllers => { registrations: 'registrations' }

  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, numericality: true
  has_one :document
  has_many :order_items
  belongs_to :category
  accepts_nested_attributes_for :document
  searchable do
      text :title, :base_price
      time :created_at
      string :base_price
      text :document do
        document.photo_file_name unless document.blank?
      end
  end


  def base_price
    price.to_i
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: :create
  load_and_authorize_resource :except => [:index, :order_history]
  skip_before_action :authenticate_user!, only: :index
  # GET /products
  # GET /products.json
  def index
    search = params[:search]
      @products = Product.search do
        fulltext search
      end
       @products = @products.results
       @order_item = current_order.order_items.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find params[:id]
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.build_document
  end

  # GET /products/1/edit
  def edit
    @product = Product.find params[:id]
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def order_history
   if current_user.is?(:admin)
      @order_history = Order.where("product_id is not null")
    else
      @order_history = current_user.orders
  end
 end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.new(product_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit! # not liking it, need to die this
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def category_ids
    Category.pluck(:name, :id)
  end

  def display_file(product)
    return "assets/unknown_product_page.jpg" if product.document.blank?
    if product.document.is_image?
         product.document.photo.path(:thumb).split('public')[1]
    elsif product.document.is_pdf?
        "assets/pdfsign.png"
    else
        "assets/unknown_product_page.jpg"
    end
  end
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class = "table">
    <tr>
    <td><%= f.label :title %></td>
    <td><%= f.text_field :title, :class=>"form-control" %></td>
  </tr>

  <tr>
    <td><%= f.label :price %></td>
    <td><%= f.text_field :price, :class=>"form-control" %></td>
  </tr>
  <tr>
    <td><%= f.label :category %></td>
    <td><%= f.select :category_id ,options_for_select(category_ids), :class=>"btn btn-primary dropdown-toggle" %></td>
  </tr>
  <tr>
    <%= f.fields_for :document do | doc |%>
    <td><%= doc.label :photo %></td>
    <td><%= doc.file_field :photo, :class=>"form-control" %></td>
    <%end%>
  </tr>
  <tr>
    <td><%= f.submit %></td>
    <td></td>
  </tr>
</table>
  <%= link_to '<<Back', products_path %>
<% end %>

app/views/products/_product_row.html.erb
<%= form_for order_item, product_id: product.id, remote: true do |f| %>
     <h6 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h6>
       <div class="input-group">
         <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
         <div class="input-group-btn">
           <%= f.hidden_field :product_id, value: product.id %>
           <%= f.submit "+Cart", :style=>"margin-left:0px", class: "btn btn-primary form-control" %>
         </div>
       </div>
 <% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
    <div id="products" class="row list-group">
      <% @products.each do | product |%>
        <div class="item  col-xs-4 col-lg-4">
            <div class="thumbnail">
             <img class="group list-group-image" src="<%= display_file(product) %>" alt="" />
                <%= product.title.truncate(20) %>
                    <p class="group inner list-group-item-text">
                      <% if product.document.present? %>
                        <% if product.document.is_pdf? %>
                        <%= link_to "Download pdf", product.document.photo.path.split("public")[1]%>
                        <%else%>
                        ...
                        <%end%>
                      <%end%>
                      </p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                        </div>
                        <div class="col-xs-12 col-md-6">
                          <%= render "product_row", product: product, order_item: @order_item %>
                       </div>
                    </div>
            </div>
        </div>
        <%end%>
    </div>
</div>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/order_history.html.erb
<table class = "table">
  <tr>
    <th>Category</th>
    <th>Prodcut Title</th>
    <th>Product Price</th>
    <th>Quantity</th>
    <th>Amount paid</th>
    <th>Order Data</th>
    <th>Status</th>
    <th>Placed By</th>
  </tr>
  <% @order_history.each do | order | %>
    <tr>
      <td><%= order.product.category.name %></td>
      <td><%= order.product.title %></td>
      <td><%= order.product.price %></td>
      <td><%= order.quantity %></td>
      <td><%= order.total%></td>
      <td><%= Date.today %></td>
      <td><span style="color: green"><%= "Pending" %></span></td>
      <td><%= link_to order.user.email, user_profile_path(id: order.user)%></td>
    </tr>
  <%end%>
</table>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>