config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
     get '/user_profile', :to => 'registrations#show'
   end
  post 'payments/verify' => "payments#verify"
  resource :cart, only: [:show]
  resources :payments, only: [:new, :create]
  resources :order_items, only: [:create, :update, :destroy], format: :js
  resources :products do
    collection do
      get "order_history"
    end
  end
  resources :categories
  devise_for :users , :controllers => { registrations: 'registrations' }

  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_cart_text.html.erb
 <%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.order_items.pluck(:total_price).inject(:+)} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<div class="footer-bottom">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<div class="copyright">
					© 2017, Kalebr, All rights reserved
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<div class="design">
					 <a href="#">Kalebr </a> |  <a target="_blank" href="http://kalebr.com/">Web Design & Development by Kalebr</a>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/products" target="_self">Kalebr</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><a data-method="delete" href="/users/sign_out"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      <% else %>
        <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <% end %>
    </ul>

    <form class="navbar-form navbar-left">
    <%= form_tag('/products', method: :get) do %>
    <div class="form-group">
      <%= text_field_tag 'search', @search, :style=>"width: 240px;", :class=>"form-control" %>
        </div>
      <%= submit_tag 'Search', :class=>"btn btn-default"%>
  </form>
  </div>
  <div id="nav-subnav" class="" >
    <div class="tabbable"> <!-- Only required for left/right tabs -->
      <ul class="nav nav-tabs">
        <% if params[:action] == "index"%>
        <li><a>Sort by category : <%= select_tag :category_id , options_for_select(Category.pluck(:name, :id)), :include_blank => "All", :class => "search_filter"%></a></li>
        <li><a>Sort by price : <%= select_tag :price , options_for_select([["High to low", 'desc'], ["Low to high", "asc"]]), :include_blank => "select", :class => "search_filter"%></a></li>
        <%end%>
        <% if user_signed_in? %>
          <li><a href="/products/order_history">Orders</a></li>
        <%end%>
        <% if can? :create, Product%>
          <li><a href="/categories/new">Add Category</a></li>
          <li><a href="/products/new">Create Product</a></li>
        <%end%>
      </ul>
    </div>
  </div>
<%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KalebrTestApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css", media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |_, message|%>
      <%= message %>
    <%end%>
    <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
  </div>
    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>